name: 'Multi-Platform Docker Build'
description: 'publish '
inputs:
  image-name:
    description: 'Image name under ghcr.io/$GITHUB_REPOSITORY'
    required: true
  tags:
    description: 'Tag name(s), space-separated, if not $GITHUB_SHA'
    default: ""
    required: true
  docker-file:
    description: 'Path of Dockerfile, if not "Dockerfile"'
    default: Dockerfile
    required: true
  path:
    description: 'Path to build, if not "."'
    default: "."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build "tag" argument
      run: |
        words=()
        tags="${{input.tags}}"
        if [ -z "$tags" ]; then
          tags="$GITHUB_SHA"
        fi
        for t in ${{ tags }}; do
          words+=("--tag" "ghcr.io/$GITHUB_REPOSITORY/${{ inputs.image-name }}:$t")
        done
        echo "tags=${words[@]}" >> $GITHUB_ENV
      shell: bash
    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username dummy --password-stdin
      shell: sh
    - name: Build the Docker image
      env:
        GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
      run: docker buildx build ${{ inputs.path }}
        --file ${{ inputs.docker-file }}
        --label org.opencontainers.image.created="$(date +'%Y-%m-%dT%H:%M:%S%z')"
        --label org.opencontainers.image.authors="$GIT_AUTHOR_NAME <tierleben-development@vkb.de>"
        --label org.opencontainers.image.source="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
        --label org.opencontainers.image.revision="$GITHUB_SHA"
        --label org.opencontainers.image.url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        $tags
        --platform=linux/amd64,linux/arm64
        --push
      shell: bash
